####
POST  http://localhost:8080/user/save
Content-Type: application/json

{
    "username": "teste",
    "email": "email",
    "hash": "hash gerado durante a criação de senha do usuário"
}
####
GET  http://localhost:8080/user/list
####
DELETE  http://localhost:8080/user/delete/9aba4e25-0626-459d-971c-284e75979037
####
GET  http://localhost:8080/h2-console