####
POST  http://localhost:8080/user/save
Content-Type: application/json

{
    "username": "teste1",
    "email": "email",
    "hash": "hash gerado durante a criação de senha do usuário"
}
####
POST  http://localhost:8080/user/save
Content-Type: application/json

{
    "username": "teste2",
    "email": "email",
    "hash": "hash gerado durante a criação de senha do usuário"
}
####
GET  http://localhost:8080/user/list
####
GET http://localhost:8080/ingestion/a4b55e36-a0de-45ca-9324-b30cba87e09a
####
DELETE  http://localhost:8080/user/delete/9aba4e25-0626-459d-971c-284e75979037
####
GET  http://localhost:8080/h2-console